[package]
name = "rust-for-rustaceans"
version = "0.1.0"
edition = "2024"

[dependencies]
ch7_proc_macro_impl = { path = "ch7_proc_macro_impl" }
rayon = "1.11.0"
tokio = {version = "1.49.0", features = ["full"]}
